name: RLMTownTour
main: com.rlminecraft.RLMTownTour.RLMTownTour
version: 1.1
author: Matt_Fielding
depend: [Towny]

commands:
  tour:
    description: Allows any non-resident to tour the existing towns for free.